In [7]:
import pandas as pd
import numpy as np
import torchvision
import torch

In [2]:
summary = pd.read_csv("../model_summary.csv")

In [3]:
summary

,model_id,k_fold,frac_val,val_best_acc,val_best_auc,val_best_sp,val_best_sn,val_avg_acc,val_avg_auc,val_avg_sp,...,host_name,is_inception,optim,lr,epochs,double_img,output_tab,backbone,feature_extract,early_start
0,32affbbcac12427a84e10af5e44db802,NaN,0.2,0.847134,0.790345,1.0,0.826087,0.769618,0.691058,0.880811,...,magneto,False,sgd,0.0100,100.0,0.0,NaN,mobile,False,100.0
1,89b1209eca2e44eeb1b59061fa687789,NaN,0.2,0.821656,0.776048,1.0,0.913043,0.725541,0.645374,0.839009,...,magneto,False,ranger,0.0100,100.0,0.0,NaN,mobile,False,100.0
2,0de11e06a2444858bcdfac8ebf136a7a,NaN,0.2,0.707006,0.530454,1.0,1.000000,0.693949,0.500441,0.967838,...,magneto,False,adam,0.0100,100.0,0.0,NaN,mobile,False,100.0
3,de2371ef299b4e109f4d8cc7b8a16d43,NaN,0.2,0.770701,0.690462,1.0,1.000000,0.616752,0.550106,0.711081,...,magneto,False,radam,0.0100,100.0,0.0,NaN,mobile,False,100.0
4,2681ca9e9e6f42c9830af1eedb7d52c6,NaN,0.2,0.757962,0.646396,1.0,1.000000,0.672675,0.515948,0.894505,...,magneto,False,radam,0.0100,100.0,0.0,NaN,mobile,False,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,5391cce51eb44cc38cd29f755613d050,NaN,0.2,0.936306,0.910693,1.0,0.956522,0.873567,0.820584,0.948559,...,magneto,False,adam,0.0005,100.0,0.0,5.0,regnet,False,100.0
600,a27d7666845242368cf1bdb1e5e4870f,NaN,0.2,0.942675,0.916765,1.0,0.934783,0.868917,0.815704,0.944234,...,magneto,False,radam,0.0010,100.0,0.0,5.0,regnet16,False,100.0
601,5df679766ba1486a8f5e4b1c65799a4e,NaN,0.2,0.923567,0.895025,1.0,1.000000,0.836306,0.773546,0.925135,...,magneto,False,ranger,0.0010,100.0,0.0,5.0,regnet16,False,100.0
602,13d7af2e91c84d88b063d3c23f29b7d1,NaN,0.2,0.936306,0.905895,1.0,0.869565,0.892866,0.836333,0.972883,...,magneto,False,adam,0.0010,100.0,0.0,5.0,regnet16,False,100.0
603,2fa497c67b724be380264a52923decb2,NaN,0.2,0.828025,0.751077,1.0,0.695652,0.760510,0.663102,0.898378,...,magneto,False,sgd,0.0010,100.0,0.0,5.0,regnet16,False,100.0

In [10]:
summary["timestamp"] = np.nan
summary["total_hours"] = np.nan
summary["average_cross_hours"] = np.nan
summary["torchvision_version"] = torchvision.__version__
summary["torch_version"] = torch.__version__

In [11]:
summary

,model_id,k_fold,frac_val,val_best_acc,val_best_auc,val_best_sp,val_best_sn,val_avg_acc,val_avg_auc,val_avg_sp,...,double_img,output_tab,backbone,feature_extract,early_start,timestamp,total_hours,average_cross_hours,torchvision_version,torch_version
0,32affbbcac12427a84e10af5e44db802,NaN,0.2,0.847134,0.790345,1.0,0.826087,0.769618,0.691058,0.880811,...,0.0,NaN,mobile,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
1,89b1209eca2e44eeb1b59061fa687789,NaN,0.2,0.821656,0.776048,1.0,0.913043,0.725541,0.645374,0.839009,...,0.0,NaN,mobile,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
2,0de11e06a2444858bcdfac8ebf136a7a,NaN,0.2,0.707006,0.530454,1.0,1.000000,0.693949,0.500441,0.967838,...,0.0,NaN,mobile,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
3,de2371ef299b4e109f4d8cc7b8a16d43,NaN,0.2,0.770701,0.690462,1.0,1.000000,0.616752,0.550106,0.711081,...,0.0,NaN,mobile,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
4,2681ca9e9e6f42c9830af1eedb7d52c6,NaN,0.2,0.757962,0.646396,1.0,1.000000,0.672675,0.515948,0.894505,...,0.0,NaN,mobile,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,5391cce51eb44cc38cd29f755613d050,NaN,0.2,0.936306,0.910693,1.0,0.956522,0.873567,0.820584,0.948559,...,0.0,5.0,regnet,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
600,a27d7666845242368cf1bdb1e5e4870f,NaN,0.2,0.942675,0.916765,1.0,0.934783,0.868917,0.815704,0.944234,...,0.0,5.0,regnet16,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
601,5df679766ba1486a8f5e4b1c65799a4e,NaN,0.2,0.923567,0.895025,1.0,1.000000,0.836306,0.773546,0.925135,...,0.0,5.0,regnet16,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
602,13d7af2e91c84d88b063d3c23f29b7d1,NaN,0.2,0.936306,0.905895,1.0,0.869565,0.892866,0.836333,0.972883,...,0.0,5.0,regnet16,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113
603,2fa497c67b724be380264a52923decb2,NaN,0.2,0.828025,0.751077,1.0,0.695652,0.760510,0.663102,0.898378,...,0.0,5.0,regnet16,False,100.0,NaN,NaN,NaN,0.13.0+cu113,1.12.0+cu113

In [12]:
summary.to_csv("../model_summary.csv", index=False)