In [1]:
import pandas as pd
import os
import numpy as np
from params import ROOT_DIR
from pathlib import Path

In [2]:
os.path.abspath('')

'/data/home/felipemarcelino/google_drive/comp_science/projects/glaucoma/notebooks'

In [4]:
labels = pd.read_excel("../oos_data.xlsx",engine)

In [5]:
labels

,Patient,date of birth,gender,eye,octdate,G (rnfl),T(rnfl),TS (rnfl),NS (rnfl),N (rnfl),NI (rnfl),TI (rnfl),Glaucoma(rnfl)
0,mg1001,1980-12-20,NaN,OD,2021-08-28,104,71,135,138,85,124,148,0
1,mg1001,1980-12-20,NaN,OS,2021-08-28,108,68,124,164,101,124,132,0
2,mg1002,1948-06-26,1.0,OD,2021-09-02,98,72,165,107,63,126,146,0
3,mg1002,1948-06-26,1.0,OS,2021-09-02,87,57,135,109,75,109,93,1
4,mg1005,1953-09-04,0.0,OD,2021-09-02,91,65,139,87,72,111,142,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,mg1079,1974-01-22,NaN,OS,2022-05-11,94,63,95,165,78,94,140,1
113,mg1081,1957-09-27,1.0,OD,2022-06-01,38,47,40,54,18,51,45,1
114,mg1081,1957-09-27,1.0,OS,2022-06-01,97,61,101,123,77,144,158,0
115,mg1082,1953-09-25,0.0,OD,2022-06-01,105,77,146,132,75,135,153,0
116,mg1082,1953-09-25,0.0,OS,2022-06-01,85,62,83,91,70,104,155,1

# EDA

In [5]:
# Remove duplicates 
labels

,Patient,date of birth,age,gender,eye (if unilateral),OCT date,G,T,TS,NS,N,NI,TI,Glaucoma
0,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,60,56,74,51,58,78,54,1
1,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,52,54,71,62,39,44,51,1
2,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,27,20,39,43,22,30,17,1
3,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,95,62,121,107,76,121,133,0
4,ADAO JOSE ANDRE 01087502,1940-11-30,"75,00",1,NaN,2015-12-15,102,52,136,153,63,145,152,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,ZENILIA DOS ANJOS,1951-06-28,"64,00",0,NaN,2015-05-29,97,64,130,122,75,118,125,0
882,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,97,72,142,92,78,111,130,0
883,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,91,65,132,88,75,103,123,0
884,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,46,41,44,62,29,54,68,1
885,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,103,64,107,188,76,118,128,0

In [6]:
len(labels[labels["Glaucoma"] == 1])/len(labels)

0.29571106094808125

In [7]:
# Almost of 30% of data has label == 1 (In other words, 30% of people have glaucoma)

In [8]:
# Get which row does not have a folder with images

In [9]:
patients_folder = os.listdir("../imgs/")

In [10]:
not_have_folder = []
id_names = labels["Patient"].values.tolist()
for patient in id_names:
    if patient in patients_folder:
        continue
    else:
        not_have_folder.append(patient)

In [11]:
not_have_folder

[]

# Join image path with labels

In [12]:
order = ["od","os"]

In [14]:
dict_data = {"Patient": [], "label": [], "photo_1": [], "photo_2": [], "eye_side": [], 
            "gender": [], "G": [], "T": [], "TS": [], "NS": [], "N": [], "NI": [], "TI": [], "age": []}
count = 0
for name, group in labels.groupby("Patient"):
    group.sort_index(inplace=True)
    folder_imgs =  os.listdir("../imgs/" + name)

    if len(group) == 2:
        count += 2
        
        
        if "MARCUS VINICI" in name:
            print(group)
            sys.exit(1)
            
        
        
        
        dict_data["Patient"].append(name)
        dict_data["Patient"].append(name)
        dict_data["label"].append(group.iloc[0]["Glaucoma"])
        dict_data["label"].append(group.iloc[1]["Glaucoma"])
        dict_data["eye_side"].append("right")
        dict_data["eye_side"].append("left")
        
        dict_data["G"].append(group.iloc[0]["G"])
        dict_data["T"].append(group.iloc[0]["T"])
        dict_data["TS"].append(group.iloc[0]["TS"])
        dict_data["NS"].append(group.iloc[0]["NS"])
        dict_data["N"].append(group.iloc[0]["N"])
        dict_data["NI"].append(group.iloc[0]["NI"])
        dict_data["TI"].append(group.iloc[0]["TI"])
        dict_data["age"].append(float(group.iloc[0]["age"].replace(",",".")))
        dict_data["gender"].append(float(group.iloc[0]["gender"]))

        
        dict_data["G"].append(group.iloc[1]["G"])
        dict_data["T"].append(group.iloc[1]["T"])
        dict_data["TS"].append(group.iloc[1]["TS"])
        dict_data["NS"].append(group.iloc[1]["NS"])
        dict_data["N"].append(group.iloc[1]["N"])
        dict_data["NI"].append(group.iloc[1]["NI"])
        dict_data["TI"].append(group.iloc[1]["TI"])
        dict_data["age"].append(float(group.iloc[1]["age"].replace(",",".")))
        dict_data["gender"].append(float(group.iloc[1]["gender"]))
       
        if "111111_Color_11MP_R_001.jpg" in list(folder_imgs):
            dict_data["photo_1"].append(Path("imgs/" + name + "/111111_Color_11MP_R_001.jpg"))
        else:
            dict_data["photo_1"].append(np.nan)
        
        if "111111_Color_11MP_R_002.jpg" in folder_imgs:
            dict_data["photo_2"].append(Path("imgs/" + name + "/111111_Color_11MP_R_002.jpg"))
        else:
            dict_data["photo_2"].append(np.nan) 
        
        if "111111_Color_11MP_L_001.jpg" in folder_imgs:
            dict_data["photo_1"].append(Path("imgs/" + name + "/111111_Color_11MP_L_001.jpg"))
        else:
            dict_data["photo_1"].append(np.nan)
        
        if "111111_Color_11MP_L_002.jpg" in folder_imgs:
            dict_data["photo_2"].append(Path("imgs/" + name + "/111111_Color_11MP_L_002.jpg"))
        else:
            dict_data["photo_2"].append(np.nan) 
    
        
    elif len(group) == 1:
        count += 1
        
        dict_data["G"].append(group.iloc[0]["G"])
        dict_data["T"].append(group.iloc[0]["T"])
        dict_data["TS"].append(group.iloc[0]["TS"])
        dict_data["NS"].append(group.iloc[0]["NS"])
        dict_data["N"].append(group.iloc[0]["N"])
        dict_data["NI"].append(group.iloc[0]["NI"])
        dict_data["TI"].append(group.iloc[0]["TI"])
        dict_data["age"].append(float(group.iloc[0]["age"].replace(",",".")))
        dict_data["gender"].append(float(group.iloc[0]["gender"]))
        dict_data["Patient"].append(name)
        dict_data["label"].append(group.iloc[0]["Glaucoma"])
        
        if group.iloc[0]["eye (if unilateral)"] == "od" or group.iloc[0]["eye (if unilateral)"] is np.nan:
            dict_data["eye_side"].append("right")
           
            if "111111_Color_11MP_R_001.jpg" in list(folder_imgs):
                dict_data["photo_1"].append(Path("imgs/" + name + "/111111_Color_11MP_R_001.jpg"))
            else:
                dict_data["photo_1"].append(np.nan)

            if "111111_Color_11MP_R_002.jpg" in folder_imgs:
                dict_data["photo_2"].append(Path("imgs/" + name + "/111111_Color_11MP_R_002.jpg"))
            else:
                dict_data["photo_2"].append(np.nan) 
        
        elif group.iloc[0]["eye (if unilateral)"] == "os" :
            
            dict_data["eye_side"].append("left")
            
           
            if "111111_Color_11MP_L_001.jpg" in folder_imgs:
                dict_data["photo_1"].append(Path("imgs/" + name + "/111111_Color_11MP_L_001.jpg"))
            else:
                dict_data["photo_1"].append(np.nan)
            if "111111_Color_11MP_L_002.jpg" in folder_imgs:
                dict_data["photo_2"].append(Path("imgs/" + name + "/111111_Color_11MP_L_002.jpg"))
            else:
                dict_data["photo_2"].append(np.nan)
        else:
            print(group.iloc[0]["eye (if unilateral)"])
            
    else:
        continue
        
        
    if len(dict_data["Patient"]) != count:
        print(count)
        print(len(dict_data["Patient"]))
        print(group)
        break

In [15]:
print(count)

886

In [16]:
path_df = pd.DataFrame.from_dict(dict_data)

In [17]:
labels

,Patient,date of birth,age,gender,eye (if unilateral),OCT date,G,T,TS,NS,N,NI,TI,Glaucoma
0,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,60,56,74,51,58,78,54,1
1,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,52,54,71,62,39,44,51,1
2,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,27,20,39,43,22,30,17,1
3,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,95,62,121,107,76,121,133,0
4,ADAO JOSE ANDRE 01087502,1940-11-30,"75,00",1,NaN,2015-12-15,102,52,136,153,63,145,152,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,ZENILIA DOS ANJOS,1951-06-28,"64,00",0,NaN,2015-05-29,97,64,130,122,75,118,125,0
882,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,97,72,142,92,78,111,130,0
883,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,91,65,132,88,75,103,123,0
884,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,46,41,44,62,29,54,68,1
885,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,103,64,107,188,76,118,128,0

In [18]:
completed_df = path_df.dropna(axis=0, subset=["photo_1","photo_2"])

In [21]:
completed_df.tail()

,Patient,label,photo_1,photo_2,eye_side,gender,G,T,TS,NS,N,NI,TI,age
881,ZENILIA GOMES ALMEIDA 10105070,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,0.0,97,72,142,92,78,111,130,72.0
882,ZENILIA GOMES ALMEIDA 10105070,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,0.0,91,65,132,88,75,103,123,72.0
883,ZILMA PEREIRA CRUZ,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,0.0,46,41,44,62,29,54,68,62.0
884,ZILMA PEREIRA CRUZ,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,0.0,103,64,107,188,76,118,128,62.0
885,edir pereira amorim 902276,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,0.0,62,50,68,81,60,89,41,73.0

In [20]:
len(completed_df[completed_df["label"] == 1])/len(completed_df)

0.28100263852242746

# Feature engineering

In [23]:
list_of_numerical_f = ["T","TS","NS","N","NI","TI"]

for idx,i in enumerate(list_of_numerical_f):
    if idx + 1 == len(list_of_numerical_f):
        break
    for edx, j in enumerate(list_of_numerical_f[idx+1:]):
        column_name = i + "/" + j
        completed_df[column_name] = completed_df[i]/completed_df[j]

/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]
/run/user/1000/ipykernel_6375/2585455741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  completed_df[column_name] = completed_df[i]/completed_df[j]

In [24]:
completed_df.head()

,Patient,label,photo_1,photo_2,eye_side,gender,G,T,TS,NS,...,TS/NS,TS/N,TS/NI,TS/TI,NS/N,NS/NI,NS/TI,N/NI,N/TI,NI/TI
0,ADALCI P SILVA 00002252,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,1.0,60,56,74,51,...,1.450980,1.275862,0.948718,1.370370,0.879310,0.653846,0.944444,0.743590,1.074074,1.444444
2,ADAO A SENA 1017456,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,1.0,27,20,39,43,...,0.906977,1.772727,1.300000,2.294118,1.954545,1.433333,2.529412,0.733333,1.294118,1.764706
3,ADAO A SENA 1017456,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,1.0,95,62,121,107,...,1.130841,1.592105,1.000000,0.909774,1.407895,0.884298,0.804511,0.628099,0.571429,0.909774
4,ADAO JOSE ANDRE 01087502,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,1.0,102,52,136,153,...,0.888889,2.158730,0.937931,0.894737,2.428571,1.055172,1.006579,0.434483,0.414474,0.953947
5,ADAO JOSE ANDRE 01087502,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,1.0,92,50,127,143,...,0.888112,2.116667,1.104348,0.992188,2.383333,1.243478,1.117188,0.521739,0.468750,0.898438

In [25]:
completed_df.to_csv("data.csv",index=None)